from typing import Dict, Any, List
from sqlalchemy.orm import Session

from agents.base_agent import BaseAgent


class AutofillAgent(BaseAgent):
    """
    Generates pre-filled content for manual steps (forms, answer templates).
    """

    def __init__(self, session: Session, event_bus, config=None):
        super().__init__(
            name="AutofillAgent",
            role="autofill",
            session=session,
            event_bus=event_bus,
            config=config or {},
        )

    def generate_for_tasks(self, blueprint_title: str, tasks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        enriched = []

        for t in tasks:
            if t.get("requires_human"):
                autofill = {
                    "note": f"Pre-fill for {blueprint_title}",
                    "suggested_answer": "This will be auto-generated by LLM in a future upgrade.",
                }
                t["autofill"] = autofill
            enriched.append(t)

        self.emit_decision(
            message=f"Generated autofill metadata for {len(enriched)} tasks.",
            payload={"tasks": enriched},
        )

        return enriched